### ISSUE TITLE
Unclear upgrade procedure

### ISSUE THREAD

**Issue by bajsicki** [ReinProject/python-rein#106]
Had some computer issues, had to reinstall Debian (kept my /home partition).

https://github.com/ReinProject/python-rein/blob/master/doc/Upgrading-v0.2-to-v0.3.md

Doesn't mention that we need to move/remove/rename local.db from ~/.rein/ after installing, or it results in errors:

>$ rein setup
Traceback (most recent call last):
  File "/usr/local/bin/rein", line 9, in <module>
    load_entry_point('rein==0.3.0', 'console_scripts', 'rein')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rein-0.3.0-py2.7.egg/rein/cli.py", line 103, in setup
    if multi or rein.has_no_account():
  File "/usr/local/lib/python2.7/dist-packages/rein-0.3.0-py2.7.egg/rein/lib/config.py", line 64, in has_no_account
    self.session.query(User).filter(User.testnet == self.testnet).count() == 0:
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 3024, in count
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2778, in scalar
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2749, in one
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2719, in one_or_none
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2790, in __iter__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2813, in _execute_and_instances
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 945, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: identity.msin [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT identity.id AS identity_id, identity.name AS identity_name, identity.contact AS identity_contact, identity.maddr AS identity_maddr, identity.msin AS identity_msin, identity.daddr AS identity_daddr, identity.dkey AS identity_dkey, identity.dxprv AS identity_dxprv, identity.will_mediate AS identity_will_mediate, identity.mediator_fee AS identity_mediator_fee, identity.enrolled AS identity_enrolled, identity.testnet AS identity_testnet \nFROM identity \nWHERE identity.testnet = ?) AS anon_1'] [parameters: (0,)]

Might be worth doing that.
--S

**Comment by weex** [comment]
Thanks for the report but of course that shouldn't be necessary. I've reinstalled Rein itself a bunch of times with an existing ~/.rein/local.db with no issues though there may be something special that happens when the dependencies are reinstalled/changed.

**Comment by weex** [comment]
Closing since the project's been on hiatus for so long that 0.2-0.3 upgrade shouldn't be a problem.
