### ISSUE TITLE
ModuleNotFoundError: No module named 'crypto'

### ISSUE THREAD

**Issue by M-O-Z-G** [ReinProject/python-rein#135]
Hi, I have installed **python-rein 0.3.1** on Windows 7 x64 with **Python 3.6 and PyCrypto 2.6.1** but when I runs '_rein start_' (or any other like _setup_, _sync_, etc.) I've got error:

```
Traceback (most recent call last):
  File "C:\Python36\Scripts\rein-script.py", line 11, in <module>
    load_entry_point('rein==0.3.1', 'console_scripts', 'rein')()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2302, in load
    return self.resolve()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python36\lib\site-packages\rein-0.3.1-py3.6.egg\rein\cli.py", line 22, in <module>
    from .lib.ui import *
  File "C:\Python36\lib\site-packages\rein-0.3.1-py3.6.egg\rein\lib\ui.py", line 7, in <module>
    from .bitcoinaddress import check_bitcoin_address
  File "C:\Python36\lib\site-packages\rein-0.3.1-py3.6.egg\rein\lib\bitcoinaddress.py", line 2, in <module>
    from crypto.util import ripemd160
ModuleNotFoundError: No module named 'crypto'
```

Before it I have tried to install **crypto** package but with the same result.

**Comment by weex** [comment]
Python-rein requires Python 2.7
