### ISSUE TITLE
rein bid invalid description error

### ISSUE THREAD

**Issue by bitspill** [ReinProject/python-rein#21]
Running from commit e2c06c9f36a058bbf7526b3150c75b85f14ac451 (master as of posting) I receive an error when attempting to check `rein bid`

```
rein bid
Traceback (most recent call last):
  File "/usr/local/bin/rein", line 9, in <module>
    load_entry_point('rein', 'console_scripts', 'rein')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/root/python-rein/rein/cli.py", line 261, in bid
    job = job_prompt(rein, jobs)
  File "/root/python-rein/rein/lib/market.py", line 71, in job_prompt
    j['Job name'], shorten(j['Description'])))
KeyError: 'Description'
```

On a different run it printed 2 jobs then failed

```
0 - bitspill - b - a
1 - weex - Enable Rein to connct over Tor - Please bid to Tor-enable Rein. The job will be considered c...
Traceback (most recent call last):
  File "/usr/local/bin/rein", line 9, in <module>
    load_entry_point('rein', 'console_scripts', 'rein')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/root/python-rein/rein/cli.py", line 251, in bid
    job = job_prompt(rein, jobs)
  File "/root/python-rein/rein/lib/market.py", line 50, in job_prompt
    j['Job name'], shorten(j['Description'])))
KeyError: 'Description'
```

**Comment by weex** [comment]
The regex that matches the name of each field in a document was greedy so 'Description' wasn't ending up in the resulting dict.

**Comment by PaulCapestany** [comment]
Was just about to submit the same issue. However, I pulled latest commits, reinstalled, and can confirm issue #21 is fixed 👍
