### ISSUE TITLE
Error while installing and running

### ISSUE THREAD

**Issue by achow101** [ReinProject/python-rein#27]
When I try to install Rein, it says it was successful, but part of the output has an error:

```
    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
  Running setup.py develop for rein

    Creating /home/andy/.local/lib/python2.7/site-packages/rein.egg-link (link to .)
    Adding rein 0.1.0 to easy-install.pth file
    Installing rein script to /home/andy/.local/bin

    Installed /home/andy/bitcoin/python-rein
Compiling /tmp/pip-build-eY9YSA/linecache2/linecache2/tests/inspect_fodder2.py ...
  File "/tmp/pip-build-eY9YSA/linecache2/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax

Successfully installed click requests python-bitcoinlib sqlalchemy unittest2 rein argparse traceback2 six linecache2
Cleaning up...
```

Then when I run it, I get

```
Traceback (most recent call last):
  File "/usr/local/bin/rein", line 9, in <module>
    load_entry_point('rein==0.1.0', 'console_scripts', 'rein')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/andy/bitcoin/python-rein/rein/cli.py", line 14, in <module>
    from lib.ui import create_account, import_account, enroll, identity_prompt, hilight
  File "/home/andy/bitcoin/python-rein/rein/lib/ui.py", line 6, in <module>
    from bitcoinecdsa import privkey_to_address, pubkey
  File "/home/andy/bitcoin/python-rein/rein/lib/bitcoinecdsa.py", line 15, in <module>
    from bitcoin.wallet import CBitcoinSecret, P2PKHBitcoinAddress
ImportError: No module named wallet
```

What am I doing wrong or is this a bug?

**Comment by weex** [comment]
Try running 'pip install bitcoin' because it looks like python-bitcoinlib doesn't satisfy that dependency which would be a bug.

**Comment by achow101** [comment]
Didn't work. Still have the problem

**Comment by weex** [comment]
What platform are you installing this on? What version of Python? Are you able to try a virtual environment?

**Comment by achow101** [comment]
I'm using ubuntu 15.10 with python 2.7.10 and pip 1.5.6. I have not tried it in a virtual environment yet as I am not sure how.

**Comment by weex** [comment]
Thanks for that info. It seems like the linecache2 package is causing a problem but it's a little hard to tell if something else is going wrong before that.

> ```
> def keyworded(*arg1, arg2=1):
>                        ^
> SyntaxError: invalid syntax
> ```

If you can please go to the python-rein folder and post the full output of:

```
$ pip install --editable .
```

Might also be helpful to see the full output of this, in case the above doesn't work.

```
$ sudo python setup.py install
```

To setup a virtual env, this is what you would do

```
$ sudo apt-get install python-dev build-essential
$ sudo pip install virtualenv
$ virtualenv v
$ . v/bin/activate
```

Then you could try installing again. That would make the installation separate from your system Python packages but then in order to run rein, you'd always have to do that last line from the directory where v exists. This can be put into your .bashrc for convenience.

**Comment by achow101** [comment]
Here is the full output of `pip install --editable .`

```
Obtaining file:///home/andy/bitcoin/python-rein
  Running setup.py (path:/home/andy/bitcoin/python-rein/setup.py) egg_info for package from file:///home/andy/bitcoin/python-rein

Downloading/unpacking click (from rein==0.1.0)
  Downloading click-6.3-py2.py3-none-any.whl (70kB): 70kB downloaded
Downloading/unpacking requests (from rein==0.1.0)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Downloading/unpacking python-bitcoinlib (from rein==0.1.0)
  Downloading python_bitcoinlib-0.5.1-py2.py3-none-any.whl (80kB): 80kB downloaded
Downloading/unpacking sqlalchemy (from rein==0.1.0)
  Downloading SQLAlchemy-1.0.12.tar.gz (4.7MB): 4.7MB downloaded
  Running setup.py (path:/tmp/pip-build-j9NrVR/sqlalchemy/setup.py) egg_info for package sqlalchemy

    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking unittest2 (from rein==0.1.0)
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB): 96kB downloaded
Downloading/unpacking argparse (from unittest2->rein==0.1.0)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Downloading/unpacking traceback2 (from unittest2->rein==0.1.0)
  Downloading traceback2-1.4.0-py2.py3-none-any.whl
Downloading/unpacking six>=1.4 (from unittest2->rein==0.1.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking linecache2 (from traceback2->unittest2->rein==0.1.0)
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: click, requests, python-bitcoinlib, sqlalchemy, unittest2, rein, argparse, traceback2, six, linecache2
  Running setup.py install for sqlalchemy
    building 'sqlalchemy.cprocessors' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/processors.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/processors.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/processors.o -o build/lib.linux-x86_64-2.7/sqlalchemy/cprocessors.so
    building 'sqlalchemy.cresultproxy' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/resultproxy.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/resultproxy.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/resultproxy.o -o build/lib.linux-x86_64-2.7/sqlalchemy/cresultproxy.so
    building 'sqlalchemy.cutils' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/utils.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/utils.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/utils.o -o build/lib.linux-x86_64-2.7/sqlalchemy/cutils.so

    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
  Running setup.py develop for rein

    Creating /home/andy/.local/lib/python2.7/site-packages/rein.egg-link (link to .)
    Adding rein 0.1.0 to easy-install.pth file
    Installing rein script to /home/andy/.local/bin

    Installed /home/andy/bitcoin/python-rein
Compiling /tmp/pip-build-j9NrVR/linecache2/linecache2/tests/inspect_fodder2.py ...
  File "/tmp/pip-build-j9NrVR/linecache2/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax

Successfully installed click requests python-bitcoinlib sqlalchemy unittest2 rein argparse traceback2 six linecache2
Cleaning up...
```

Here is the full output of `sudo python setup.py install`

```
running install
running bdist_egg
running egg_info
writing requirements to rein.egg-info/requires.txt
writing rein.egg-info/PKG-INFO
writing top-level names to rein.egg-info/top_level.txt
writing dependency_links to rein.egg-info/dependency_links.txt
writing entry points to rein.egg-info/entry_points.txt
reading manifest file 'rein.egg-info/SOURCES.txt'
writing manifest file 'rein.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/rein
copying rein/__init__.py -> build/lib.linux-x86_64-2.7/rein
copying rein/cli.py -> build/lib.linux-x86_64-2.7/rein
creating build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/config.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/script.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/bitcoinecdsa.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/placement.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/order.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/validate.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/bitcoinaddress.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/document.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/user.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/models.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/__init__.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/market.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/bucket.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/toolbox.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/ui.py -> build/lib.linux-x86_64-2.7/rein/lib
copying rein/lib/bitcoinsig.py -> build/lib.linux-x86_64-2.7/rein/lib
creating build/lib.linux-x86_64-2.7/rein/lib/network
copying rein/lib/network/__init__.py -> build/lib.linux-x86_64-2.7/rein/lib/network
creating build/lib.linux-x86_64-2.7/rein/lib/crypto
copying rein/lib/crypto/__init__.py -> build/lib.linux-x86_64-2.7/rein/lib/crypto
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/rein
creating build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/config.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/script.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/bitcoinecdsa.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/placement.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/order.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/validate.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/bitcoinaddress.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/document.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/user.py -> build/bdist.linux-x86_64/egg/rein/lib
creating build/bdist.linux-x86_64/egg/rein/lib/network
copying build/lib.linux-x86_64-2.7/rein/lib/network/__init__.py -> build/bdist.linux-x86_64/egg/rein/lib/network
copying build/lib.linux-x86_64-2.7/rein/lib/models.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/__init__.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/market.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/bucket.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/toolbox.py -> build/bdist.linux-x86_64/egg/rein/lib
creating build/bdist.linux-x86_64/egg/rein/lib/crypto
copying build/lib.linux-x86_64-2.7/rein/lib/crypto/__init__.py -> build/bdist.linux-x86_64/egg/rein/lib/crypto
copying build/lib.linux-x86_64-2.7/rein/lib/ui.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/lib/bitcoinsig.py -> build/bdist.linux-x86_64/egg/rein/lib
copying build/lib.linux-x86_64-2.7/rein/__init__.py -> build/bdist.linux-x86_64/egg/rein
copying build/lib.linux-x86_64-2.7/rein/cli.py -> build/bdist.linux-x86_64/egg/rein
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/script.py to script.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/bitcoinecdsa.py to bitcoinecdsa.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/placement.py to placement.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/order.py to order.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/validate.py to validate.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/bitcoinaddress.py to bitcoinaddress.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/document.py to document.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/user.py to user.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/network/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/market.py to market.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/bucket.py to bucket.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/toolbox.py to toolbox.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/crypto/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/ui.py to ui.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/lib/bitcoinsig.py to bitcoinsig.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/rein/cli.py to cli.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying rein.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/rein-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing rein-0.1.0-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/rein-0.1.0-py2.7.egg
Extracting rein-0.1.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing rein 0.1.0 from easy-install.pth file
Adding rein 0.1.0 to easy-install.pth file
Installing rein script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/rein-0.1.0-py2.7.egg
Processing dependencies for rein==0.1.0
Searching for unittest2==1.1.0
Best match: unittest2 1.1.0
Adding unittest2 1.1.0 to easy-install.pth file
Installing unit2 script to /usr/local/bin

Using /home/andy/.local/lib/python2.7/site-packages
Searching for SQLAlchemy==1.0.12
Best match: SQLAlchemy 1.0.12
Adding SQLAlchemy 1.0.12 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for python-bitcoinlib==0.5.1
Best match: python-bitcoinlib 0.5.1
Adding python-bitcoinlib 0.5.1 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for requests==2.9.1
Best match: requests 2.9.1
Removing requests 2.7.0 from easy-install.pth file
Adding requests 2.9.1 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for click==6.3
Best match: click 6.3
Adding click 6.3 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Removing six 1.9.0 from easy-install.pth file
Adding six 1.10.0 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for traceback2==1.4.0
Best match: traceback2 1.4.0
Adding traceback2 1.4.0 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for argparse==1.4.0
Best match: argparse 1.4.0
Adding argparse 1.4.0 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Searching for linecache2==1.0.0
Best match: linecache2 1.0.0
Adding linecache2 1.0.0 to easy-install.pth file

Using /home/andy/.local/lib/python2.7/site-packages
Finished processing dependencies for rein==0.1.0
```

This is the output of installing in a virtual environment:

```
Obtaining file:///home/andy/bitcoin/python-rein
Collecting click (from rein==0.1.0)
  Using cached click-6.3-py2.py3-none-any.whl
Collecting requests (from rein==0.1.0)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting python-bitcoinlib (from rein==0.1.0)
  Using cached python_bitcoinlib-0.5.1-py2.py3-none-any.whl
Collecting sqlalchemy (from rein==0.1.0)
Collecting unittest2 (from rein==0.1.0)
  Using cached unittest2-1.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2->rein==0.1.0)
Collecting traceback2 (from unittest2->rein==0.1.0)
  Using cached traceback2-1.4.0-py2.py3-none-any.whl
Collecting six>=1.4 (from unittest2->rein==0.1.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting linecache2 (from traceback2->unittest2->rein==0.1.0)
  Using cached linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: click, requests, python-bitcoinlib, sqlalchemy, linecache2, traceback2, six, unittest2, rein
  Running setup.py develop for rein
Successfully installed click-6.3 linecache2-1.0.0 python-bitcoinlib-0.5.1 rein requests-2.9.1 six-1.10.0 sqlalchemy-1.0.12 traceback2-1.4.0 unittest2-1.1.0
```

and this is the output of running rein in the virtual environment:

```
Traceback (most recent call last):
  File "/home/andy/bitcoin/python-rein/v/bin/rein", line 9, in <module>
    load_entry_point('rein', 'console_scripts', 'rein')()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/andy/bitcoin/python-rein/rein/cli.py", line 28, in <module>
    import lib.models
  File "/home/andy/bitcoin/python-rein/rein/lib/models.py", line 18, in <module>
    Base.metadata.create_all(engine)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
    tables=tables)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/andy/bitcoin/python-rein/v/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

**Comment by weex** [comment]
Ahh, are you running master? We need to do a release since a number of fixes have happened since the alpha.

In regards to the original error, I got the same error as you on 15.10 but `sudo python setup.py install` cleared the error. I guess I've been testing mostly inside a virtualenv and that did not show the error with pip install --editable .

My guess is there's something that isn't getting written outside a virtualenv and without sudo.

Thanks for working through this. Can you try it with master?

**Comment by achow101** [comment]
With master, if I install it as my normal user, I get

```
Obtaining file:///home/andy/bitcoin/python-rein
Requirement already satisfied (use --upgrade to upgrade): click in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): python-bitcoinlib in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): unittest2 in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2->rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): traceback2 in /home/andy/.local/lib/python2.7/site-packages (from unittest2->rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /home/andy/.local/lib/python2.7/site-packages (from unittest2->rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): linecache2 in /home/andy/.local/lib/python2.7/site-packages (from traceback2->unittest2->rein==0.1.0)
Installing collected packages: rein
  Running setup.py develop for rein
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/home/andy/bitcoin/python-rein/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    error: can't create or remove files in install directory

    The following error occurred while trying to add or remove files in the
    installation directory:

        [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-19770.write-test'

    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /usr/local/lib/python2.7/dist-packages/

    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.

    For information on other options, you may wish to consult the
    documentation at:

      https://pythonhosted.org/setuptools/easy_install.html

    Please make the appropriate changes for your system and try again.


    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/andy/bitcoin/python-rein/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/andy/bitcoin/python-rein/
```

If I use sudo, I get:

```
The directory '/home/andy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/andy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/andy/bitcoin/python-rein
Requirement already satisfied (use --upgrade to upgrade): click in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): python-bitcoinlib in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): unittest2 in /home/andy/.local/lib/python2.7/site-packages (from rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2->rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): traceback2 in /home/andy/.local/lib/python2.7/site-packages (from unittest2->rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /home/andy/.local/lib/python2.7/site-packages (from unittest2->rein==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): linecache2 in /home/andy/.local/lib/python2.7/site-packages (from traceback2->unittest2->rein==0.1.0)
Installing collected packages: rein
  Running setup.py develop for rein
Successfully installed rein-0.1.0
```

After installing with sudo, when I ran the program it still had the same error. I also had the same error after running `sudo python setup.py install`

It works in a virtualenv though.

**Comment by weex** [comment]
It should create the db and config_dir if they don't exist on each run. Clearly we need more help fixing installation so it can work with and without the virtual environment.

**Comment by weex** [comment]
1f12672227bd14da3071badd6655adb07a92aeb4 improves this by taking away the linecache2 error outside a virtualenv

**Comment by weex** [comment]
Updated readme to use sudo on install and remove virtualenv requirement. Tested on Ubuntu 15.10.
