### ISSUE TITLE
Updating Rein isn't described anywhere, and installing new version over old breaks all functionality

### ISSUE THREAD

**Issue by bajsicki** [ReinProject/python-rein#93]
So I wanted to update Rein, given that my version was... old, to say the least.

Here's what I did:

`$ git clone https://github.com/ReinProject/python-rein.git ~/python-rein`
`$ cd python-rein`
`$ sudo pip install`

Now, rein 'works', in that running `rein` results in the normal list of commands. But when I do `rein status`, I get this:

Traceback (most recent call last):
  File "/usr/local/bin/rein", line 11, in <module>
    load_entry_point('rein==0.2.0', 'console_scripts', 'rein')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rein/cli.py", line 1062, in status
    (log, user, key, urls) = init(multi, identity)
  File "/usr/local/lib/python2.7/dist-packages/rein/cli.py", line 1170, in init
    if rein.has_no_account():
  File "/usr/local/lib/python2.7/dist-packages/rein/lib/config.py", line 64, in has_no_account
    self.session.query(User).filter(User.testnet == self.testnet).count() == 0:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3031, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2785, in scalar
    ret = self.one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2756, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2726, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2797, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2820, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: identity.dxprv [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT identity.id AS identity_id, identity.name AS identity_name, identity.contact AS identity_contact, identity.maddr AS identity_maddr, identity.daddr AS identity_daddr, identity.dkey AS identity_dkey, identity.dxprv AS identity_dxprv, identity.will_mediate AS identity_will_mediate, identity.mediator_fee AS identity_mediator_fee, identity.enrolled AS identity_enrolled, identity.testnet AS identity_testnet \nFROM identity \nWHERE identity.testnet = ?) AS anon_1'] [parameters: (0,)]

**Comment by weex** [comment]
Right now, the way to update would be to insert the command
`git checkout v0.2.4-alpha`
before running the installer.

**Comment by weex** [comment]
The howto has been updated.
